### ISSUE TITLE
Database need to add pg_hba whitelist

### ISSUE THREAD

**Issue by Ghostbaby** [goharbor/harbor-cluster-operator#114]
```yaml
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
    - hostssl all all 0.0.0.0/0 md5
    - host    all all 0.0.0.0/0 md5
```
