### ISSUE TITLE
Wrong Minio registry storage secret, should not use empty string when not specify some feilds.

### ISSUE THREAD

**Issue by wangcanfengxs** [goharbor/harbor-cluster-operator#120]
The values in HarborCluster
```
    storage:
      kind: s3
      s3:
        accesskey: AKIAIOSFODNN7EXAMPLE
        bucket: harbor
        chunksize: "5242880"
        region: us-west-1
        regionendpoint: http://all-in-one-minio.default.svc.cluster.local:9000
        secretkey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```

The generated secret value(base64 decoded):
```
{
    "accesskey":"AKIAIOSFODNN7EXAMPLE",
    "bucket":"harbor",
    "chunksize":"5242880",
    "encrypt":"false",
    "keyid":"",
    "region":"us-west-1",
    "regionendpoint":"http://all-in-one-minio.default.svc.cluster.local:9000",
    "rootdirectory":"",
    "secretkey":"wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
    "secure":"false",
    "storageclass":"",
    "v4auth":"false"
}
```

The keyid and storageclass is empty string, but not omited.
These will cause one problem, for example, the storageclass should not be empty. The registry will crash.

```
panic: The storageclass parameter must be one of [NONE STANDARD REDUCED_REDUNDANCY],  invalid

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x1115e60, 0xc000128a50, 0xc0004e2380, 0x0)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:126 +0x2e7d
github.com/docker/distribution/registry.NewRegistry(0x1115e60, 0xc0004854d0, 0xc0004e2380, 0x5, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:105 +0x218
github.com/docker/distribution/registry.glob..func1(0x18b4ae0, 0xc0003b61d0, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:63 +0x188
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x18b4ae0, 0xc0003b60e0, 0x1, 0x1, 0x18b4ae0, 0xc0003b60e0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x191
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x18b4c80, 0xc000515f88, 0xc0000a2058)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x2b2
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x2d


```
