### ISSUE TITLE
Error: container has runAsNonRoot and image has non-numeric user (nonroot), cannot verify user is non-root

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-cluster-operator#166]
- missing `securityContext` in related `kustomization` yaml files
```yaml
securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
```
- `Dockerfile` use non numberic nonroot user `nonroot`

```shell
USER nonroot:nonroot
```

==>

```shell
USER 1000:1000
```
