### ISSUE TITLE
duplicate storage config in registry config yaml file

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-cluster-operator#167]
```yaml
storage:
  delete:
    enabled: true
  redirect:
    disable: false
  cache:
    blobdescriptor: redis
  maintenance:
    uploadpurging:
      enabled: false
    readonly:
      enabled: false
  s3:
    accesskey: wksnzucl
    bucket: harbor
    encrypt: "false"
    region: us-east-1
    regionendpoint: http://sz-harbor-cluster-minio.sample.svc:9000
    secretkey: pakjrkha
    secure: "false"
    v4auth: "false"

  s3:
    accesskey: wksnzucl
    bucket: harbor
    encrypt: "false"
    region: us-east-1
    regionendpoint: http://sz-harbor-cluster-minio.sample.svc:9000
    secretkey: pakjrkha
    secure: "false"
    v4auth: "false"
```
