### ISSUE TITLE
Error when execute `make run`

### ISSUE THREAD

**Issue by wangcanfengxs** [goharbor/harbor-cluster-operator#54]
when execute `make run`, there will generate a file `config/crd/bases/goharbor.goharbor.io_harborclusters.yaml` which includes the crd definition.

But when I apply this yaml file. I get something error.

**Error**

```
The CustomResourceDefinition "harborclusters.goharbor.goharbor.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[imageSource].default: Forbidden: must not be set
```

**The YAML snippet about this file**

```
            imageSource:
              default:
                registry: docker.io
              description: Source registry of images, the default is dockerhub
              properties:
                imagePullSecret:
                  type: string
                registry:
                  type: string
              type: object
```
