### ISSUE TITLE
The resource definition MAY By wrong.

### ISSUE THREAD

**Issue by wangcanfengxs** [goharbor/harbor-cluster-operator#56]
**The code**
```
type PostgresSQL struct {
	Storage          string              `json:"storage,omitempty"`
	Replicas         int                 `json:"replicas,omitempty"`
	Version          string              `json:"version,omitempty"`
	StorageClassName string              `json:"storageClassName,omitempty"`
	Resources        corev1.ResourceList `json:"resources,omitempty"`

	// External params following.
	// The secret must contains "address:port","usernane" and "password".
	SecretName     string `json:"secretName,omitempty"`
	SslConfig      string `json:"sslConfig,omitempty"`
	ConnectTimeout int    `json:"connectTimeout,omitempty"`
}

// ResourceList is a set of (resource name, quantity) pairs.
type ResourceList map[ResourceName]resource.Quantity

```

**The doc**

```YAML
  database:
    kind: inCluster
    spec:
      storage: 1Gi
      replicas: 2
      version: "12"
      # optional
      storageClassName: default
      # optional
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 250Mi
```

Where is the `limits` and `requests`?

If you want to using resource LIKE k8s, you SHOULE define strcut like this:
```
// ResourceRequirements describes the compute resource requirements.
type ResourceRequirements struct {

	Limits ResourceList `json:"limits,omitempty"`

	Requests ResourceList `json:"requests,omitempty"`
}
```
